### ISSUE TITLE
Getting logs from remote sources

### ISSUE THREAD

**Issue by DigiAngel** [controlscanmdr/cyphon#177]
So first off it's good to be back :)  Thanks for the ova..just what I needed to remove the docker layer.  So ok...I'm following this:

[logstash](https://cyphon.readthedocs.io/en/latest/tutorials/logstash-tutorial.html)

and right off this *appears* from the Prospector and Output sections that the assumption is that snort is running ON the Cyphon box...is that the case in the tutorial?  I'm currently sending logs from remote sources.  I have a functioning logstash  on a different setup listening to different ports for different types of data like:
~~~
logtype 1 port 8700
logtype 2 port 8701
etc...
~~~

I each port has a different type tag which let's me know what kind it is.  It appear that's not the way Cyphon does it.  I'd like to know how to setup Cyphon to, at first, remotely ingest a log source and go from there.  I have the latest ova VM up and running (thanks again!).  Thank you!

**Comment by lhadjchikh** [comment]
Nice to have you back! :-)

Snort can be running on a different box. You just need to configure Filebeat to point to your Logstash server, wherever that may be. ("localhost" is Filebeat's default setting, so you'll need to change that.)

Cyphon doesn't talk to Logstash directly; it just talks to RabbitMQ. The VM is running a Cyphondock production deployment, which exposes Logstash ports but not RabbitMQ. If you want to use Logstash on a different server (outside the VM), you'll need to edit the ``docker-compose.override.yml`` file on the VM to expose RabbitMQ:
```
  rabbit:
    ports:
      - "5672:5672"
```
You'll then need to point your Logstash output to RabbitMQ, similar to what's shown [here](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/3-output.conf#L46-L76) (but you'll need to change the host setting to the IP address of your VM). In your Logstash filter, be sure to generate a uuid and add a field that points to the location of the document in Elasticsearch (as shown [here](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/2-filter5-cyphon.conf)), and make sure you're using the uuid for the Elasticsearch document_id (as shown [here](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/3-output.conf#L9-L37)). This information is required to allow Cyphon to locate the document. Note that you'll be sending docs to both Elasticsearch (for storage) and RabbitMQ (for Alert generation by Cyphon).

You might find the discussion in https://github.com/dunbarcyber/cyphon/issues/172 useful for understanding what's going on.

**Comment by DigiAngel** [comment]
Thank you.  So...a) I'm guessing you mean filebeat running on the *remote* snort machine yes?  My desire is just to point the snort machine -> cyphon and not have any other middle man.  Currently snort logs are getting shipped via rsyslog which is reading the snort alert file.  Is there a way I can get rsyslog to ship directly to cyphon, or do you recommend installing filebeat on the remote snort machine?

**Comment by lhadjchikh** [comment]
Yes, Filebeat would go on the remote Snort machine. Cyphon doesn't really care how you're shipping the messages from your remote server, but it needs to be able to retrieve them from RabbitMQ, because it uses queue consumers to process the messages (this is done through the [receiver package](http://cyphon.readthedocs.io/en/latest/modules/receiver.html)). Logstash makes it easy to send things to RabbitMQ, and Filebeat make it easy to send things to Logstash, so that's the method we currently use.

**Comment by DigiAngel** [comment]
Ok perfect....so now....it appears that I could do something like the below:

snortlog via udp -> Logstash on Cyphon listening port 9000 -> RabbitMQ

I'm taking this slow so I understand...right now my first step is to get the data from snort...does the above make sense so far?

**Comment by lhadjchikh** [comment]
Close! :-)  It's more like: snortlog via udp -> Logstash -> RabbitMQ -> Cyphon. If you can get the logs into Logstash, you then just need to make sure that both Logstash and Cyphon are pointing at the same RabbitMQ server. For Logstash, you'd configure this in the [output plugin](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/3-output.conf#L46-L76), and for Cyphon, you'd configure it your [conf.py](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/cyphon/settings/conf.py#L199-L207) or [.env](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/env/cyphon.env#L19-L22) file.

**Comment by DigiAngel** [comment]
LoL ok cool....since I'm running Cyphon from the ova, my assumption is that Logstash, RabbitMQ, and, obviously, Cypon are all there.  So if that's the case, do I just configure an input in logstash.conf for snort to send to first?

**Comment by lhadjchikh** [comment]
Logstash on the VM is already listening on ports 5044 and 5045 (you can expose more ports [here](https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.override.yml#L15-L18)). It's using the configs in the [pipeline](https://github.com/dunbarcyber/cyphondock/tree/master/config-COPYME/logstash/pipeline) folder, so if you need to make any changes to Logstash inputs, filters, or outputs, make them there. If you want to use a Logstash instance running outside the VM, expose the RabbitMQ port on the VM as mentioned above, and point Logstash's RabbitMQ output there (your VM's IP address and port 5672).

**Comment by DigiAngel** [comment]
Ok great....I'll give this a shot and report my findings...thank you!

**Comment by suchandbabu** [comment]
This discussion gives a lot of information for me regarding logstash , rabbitmq and cyphon integration.
Thank you.

Can you please let me know how can I find out uuid of my elasticsearch ruining in cyphondock.

Here I am trying to send logs from a logstash instance to the rabbitmq and elasticsearc running in another instance(cyphondock instance)

Can you please help me with this.

**Comment by lhadjchikh** [comment]
@suchandbabu If you need to access the Elasticsearch container from an external Logstash instance, you can modify the `docker-compose-override.yml` file to bind port 9200 as you suggest:
```
  elasticsearch:
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
```
When sending logs to RabbitMQ for alert generation by Cyphon, you'll need to send them to a watchdogs queue by adding `key => "watchdogs"` to your RabbitMQ output in your Logstash config. (This assumes you have at least one watchdog container running in Cyphondock to consume that queue.)

Keep in mind, watchdogs just generate alerts; they don't save raw data (except the data associated with an alert). Cyphon won't actually save any logs to Elasticsearch unless you send logs to a "logchutes" (`key => "logchutes"`) or "datachutes" (`key => "datachutes"`) queue and have the corresponding service(s) running in Cyphondock.

It's probably best to have Logstash save the data to Elasticsearch and just send a copy to RabbitMQ for alert generation by Cyphon. This is how Cyphondock is currently set up.

As you mention, you can check on RabbitMQ queues and consumers by visiting port 15672, which is the RabbitMQ Management dashboard.
