### ISSUE TITLE
Where to start translating Cyphon?

### ISSUE THREAD

**Issue by ghost** [controlscanmdr/cyphon#210]
Hello
I want to translate Cyphon but i don't know how i can translate it.
Where is the start point?

**Comment by lhadjchikh** [comment]
Cyphon's backend is based on the Django web framework, which has a lot of support for translation. You can read about it [here](https://docs.djangoproject.com/en/1.11/topics/i18n/). 

Unfortunately, we haven't taken full advantage of this yet, so most of the settings are currently only available in English. Translating the project will require consistent use of [translation strings](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#internationalization-in-python-code) in the code. You can see an example on [StackOverflow](https://stackoverflow.com/questions/2938692/django-internationalization-for-admin-pages-translate-model-name-and-attribute).

Currently, translation will be patchy, but you can set the default language by changing the ``LANGUAGE_CODE`` setting in your ``cyphon/settings/base.py`` file. You can comment out ``'django.middleware.locale.LocaleMiddleware'`` in the ``MIDDLEWARE_CLASSES`` setting if you want to be sure it uses the ``LANGUAGE_CODE`` setting. See [Django's docs](https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#how-django-discovers-language-preference) for more details.

**Comment by lhadjchikh** [comment]
I created a [feature/internationalization](https://github.com/dunbarcyber/cyphon/tree/feature/internationalization) branch so folks can work on this. Feel free to fork it if you'd like to contribute. I also promise to be more diligent about using translation strings from now on. :-)

**Comment by Vahid-Nameni** [comment]
Thank You!
