### ISSUE TITLE
Time and Frequency Based Alarm Criteria

### ISSUE THREAD

**Issue by kfiducia** [controlscanmdr/cyphon#270]
An ability to configure alarms based on their frequency and time, for instance:
- The first time a certain value in a certain data field is seen in a dataflow; e.g. new host on a network
- n-th time a similar (all but time match) dataflow is seen and the last x period of time; e.g. n failed logins in the past x minutes; the first failed login certainly doesn't need a critical alarm, but the 20th in 2 minutes might indicate a brute force attack.

**Comment by ziednamouchi** [comment]
Yes It will be great to have this feature. For example with IDS. If I receive n ICMP requests from a certain range of IP@, or if the number, of ICMP requests is superior to a fixed number an alert is generated and the severity level is set automatically to HIGH or CRITICAL (for example)
