### ISSUE TITLE
loglevel doesnt propagate to modules imported by receiver

### ISSUE THREAD

**Issue by adamstauffer** [controlscanmdr/cyphon#397]
im trying to add debug level log statements in `watchdogs/models.py` to debug why watchdogs are not creating alerts for certain data. however, when changing log levels for the receiver in my [settings/prod.py](https://github.com/dunbarcyber/cyphon/blob/master/cyphon/cyphon/settings/prod.example.py), i cant get these messages to show in the console or in the receiver.log file. upon further investigation, the log level is getting set properly in the `receiver.py` module upon load. however inside the `watchdogs/models.py` file, the logger there has a level of NOTSET (expected), but the root logger still has the default level of WARN, which is why debug messages wont show

likely need to find a way for the receiver to propagate its loglevel to imported modules or override the root logger from this module

**Comment by lhadjchikh** [comment]
Watchdog messages are controlled by the `LOGGING['loggers']['django']` setting, so I would try changing that level to `DEBUG` (although you'll probably end up seeing a lot of other logs, too). Alternatively, you could try changing the `_LOGGER` setting in `watchdogs/models.py` to `logging.getLogger('receiver')`, like it is in `receiver/receiver.py`.

**Comment by adamstauffer** [comment]
changing that doesnt seem to work for me. im using docker with prod settings. i changed the `level` in the other loggers and config files too for good measure

i am able to use the receiver logger in other modules, so that works for my purposes. i was thinking about pushing some of these log statements in case they helpful for others who are debugging watchdogs (and maybe as a workaround/starting point for #268).  

ill have to look into how django handles logging to investigate more,

**Comment by adamstauffer** [comment]
the only thing ive been able to make work is by overriding the root logger configuration in my `settings/prod.py`. ill push the logging changes anyway. feel free to close this issue if unable to reproduce
