### ISSUE TITLE
Recursive Bottle causes 502 Bad Gateway disruption

### ISSUE THREAD

**Issue by kfiducia** [controlscanmdr/cyphon#409]
Not as much of a bug as just being able to catch an error for the user - if you accidentally create a recursive bottle (a bottle that references an embedded doc that references the parent) then the admin interface times out as one could predict if they knew what they did. Maybe not catch the error in config, but fail more gracefully (timeout on the request handled better).

**Comment by lhadjchikh** [comment]
Thanks! I would definitely call this a bug. I had discovered a similar problem a while back with recursive sieves, and fixed it with some extra [validation](https://github.com/dunbarcyber/cyphon/blob/master/cyphon/sifter/sieves/models.py#L559-#L571).  I'll see if I can do something similar to prevent users from creating recursive bottles.
