### ISSUE TITLE
Improvement. Creating reports

### ISSUE THREAD

**Issue by trenerok** [controlscanmdr/cyphon#412]
I think it would be very good to have the opportunity in Cyphon to generate a report on the incidents. For example: the ability to form an incident by criticality levels, by the type of incidents, by the processed incidents over the period. It would also be very good to choose certain fields from the incident and include them in the report. To take into report recent actions and comments on the incident.
Also Number of processed incidents per employee.

**Comment by cybersecc** [comment]
Yes, it is a good idea. I think it will be awesome if Cyphon could generate daily/monthly reports and be able to send them over smtp

**Comment by zpycho** [comment]
Definitely, it will be very helpful
