### ISSUE TITLE
Cyphon Ubuntu Server ISO Installation Fails

### ISSUE THREAD

**Issue by hackdefendr** [controlscanmdr/cyphon#413]
I get as far as the partitioning screen, I choose Manual, and it immediately shows a Red error page claiming there is no root partition. I wasn't given the chance to create any partitions.

As a test, I downloaded the same version Ubuntu Server (16.0.4.3), and did not have any problems partitioning my drives. No errors.

So something is different (besides the obvious) between the Cyphon ISO and a standard Ubuntu Server ISO.

**Comment by darvid** [comment]
Manual partitioning is not currently supported by the installer but hopefully will be in the future. If I enter the desired size during partitioning and let it auto-partition, everything installs normally for me.

Could you try installing without manual partitioning and see if that works for you? Your vmdisk should be at least 20 GiB.

**Comment by hackdefendr** [comment]
Well I was actually installing this on physical hardware that has a boot drive and a striped raid for the root partition.  I really need the manual partition option.

**Comment by darvid** [comment]
@hackdefendr [Here's an updated ISO](https://s3.amazonaws.com/cyphon-public/vms/cyphon-ubuntu-server-16.04.3-lts-fullpartman.iso) that enables the full partition manager in the preseed. I attempted to setup LVM and RAID0 in QEMU and it seemed to work for me. Let me know if you have any issues.

**Comment by hackdefendr** [comment]
Awesome... I will try it tonight.

**Comment by hackdefendr** [comment]
Ack! No EFI...well, I went ahead and installed server, then ran the postinstall.  I think everything is working properly at this point.

**Comment by hackdefendr** [comment]
Take that back.  It doesn't appear things are working. 

Elasticsearch STATUS shows Restarting (1) and never comes up.

Trying to access the Nginx gateway to Cyphon displays a ERR_CONNECTION_CLOSED error.

Did I miss something after the postinstall script?

**Comment by darvid** [comment]
Sorry for the delay. Can you check the Elasticsearch logs?

```docker logs -f cyphondock_elasticsearch_1```

I suspect it's a permissions issue, although the postinstall script should apply the correct ownership to the data directories for Elasticsearch...

**Comment by hackdefendr** [comment]
I think there is a step missing somewhere.  I have wiped my docker folder and started fresh a couple of times now and the results remain the same. Several services are not coming up at all...like, postgresql, rabbit, elasticsearch, etc.  

I will try again tonight and see what the logs say on each of the services that don't start up properly.

Thanks,

**Comment by hackdefendr** [comment]
Nope not a permissions issue it appears.  Both elasticsearch and postgresql are populating their respective data folders. All of the containers have healthy status, but I still cannot access the Cyphon web ui...I get ERR_CONNECTION_REFUSED.

**Comment by hackdefendr** [comment]
I'd like to retry the ISO method.  Could you make one that supports EFI and has the partition creator built in?

**Comment by fatalglitch** [comment]
We are working to have a new updated ISO available next week with EFI support, and further customization capability

**Comment by hackdefendr** [comment]
Excellent.  Thanks!

**Comment by daveacquitygroup** [comment]
> Take that back. It doesn't appear things are working.
> 
> Elasticsearch STATUS shows Restarting (1) and never comes up.
> 
> Trying to access the Nginx gateway to Cyphon displays a ERR_CONNECTION_CLOSED error.
> 
> Did I miss something after the postinstall script?

This is a common issue. You need to change the Java virtual memory size for the host not the container and it should run just fine. see this article on how to enlarge this https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
