### ISSUE TITLE
Add ability to show other alert fields in waterfall view

### ISSUE THREAD

**Issue by ghost** [controlscanmdr/cyphon#414]
why not add a new field for alerts. When we click on the button alerts and the list of alerts displayed, we have not only the name of the watchdog It is also possible to add another field that will serve as a label (for example the name of the machine host from which alerts are coming). 
Like that, if we collect the same type of log of different machines we can both have the type of the alert if it is an alert snort, nessus or other and at the same time have the name of the machine that generates this log.
![cyclops](https://user-images.githubusercontent.com/35686392/36693825-c3d79d08-1b3c-11e8-84d5-b59e74eb3485.jpg)

**Comment by trenerok** [comment]
Yes I would like to add different fields.
