### ISSUE TITLE
Cannot connect to amqp://guest:**@rabbit:5672 ERROR

### ISSUE THREAD

**Issue by p3nreel** [controlscanmdr/cyphon#595]
Hello All,
I installed Cyphon via docker and have successfully followed the tutorial to send email alerts to Cyphon. Cyphon is receiving the emails fine but it is not generating an alert. I get the error message below when running the command "docker logs -f cyphon_dock_celeryworker_1_". From looking at the password info and other settings, everything seems correct. Any ideas what could be causing this? Thanks in advance.

![log_1](https://user-images.githubusercontent.com/19589960/42112697-afd291ca-7bb6-11e8-9c6f-4410875dcd8e.JPG)

**Comment by lhadjchikh** [comment]
Were there any errors in the logs for the RabbitMQ docker container?
```
docker logs -f cyphondock_rabbit_1
```
And are you able to access the RabbitMQ management panel? This would be at http://localhost:15672 on the host machine if you're running in production mode.  (If you're running in dev mode, you'll need to find out what port it's using on the host machine.)

**Comment by p3nreel** [comment]
Hello, there were no errors in the RabbitMQ container. I am able to access the management console. Please see below for more info. Is there any other logs I can provide that might be helpful?

![cyphon info](https://user-images.githubusercontent.com/19589960/42236727-b297518c-7ec9-11e8-9185-acc02452c1b3.jpg)

**Comment by chasebrewsky** [comment]
You don't have `guest` defined in your `default.py`. Have you defined a python dictionary named `guest` somewhere in your settings?

**Comment by p3nreel** [comment]
Thanks Chase, I'm not sure I understand correctly. I see 2 areas in the default.py file that relates to RABBITMQ. Both username and password is set to default (see below). Right now I am still in the testing phase but once Cyphon is up and running, I will change the username/password to something more complex. Is the current configuration I have wrong? I don't recall making any change to a python dictionary named "guest". Is there somewhere in the documentation that can give me guidance on this?Thanks in advance.

**Comment by chasebrewsky** [comment]
Your BROKER_URL should look like this:

```
BROKER_URL = 'amqp://{username}:{password}@{host}:5672/{vhost}'.format(
    username=RABBITMQ['USERNAME'],
    password=RABBITMQ['PASSWORD'],
    host=RABBITMQ['HOST'],
    vhost=RABBITMQ['VHOST']
)
```

Note the lack of `guest['USERNAME']` and `guest['PASSWORD']`.

**Comment by p3nreel** [comment]
Thanks Chase, I'll make this change and retest.

**Comment by p3nreel** [comment]
Hello, I made the change but still getting the same error. Below are the current configs. I'm open to more suggestions. Thanks!
![rabbitmq](https://user-images.githubusercontent.com/19589960/42663634-58ea93d2-8604-11e8-996f-a6ea06c6ab63.JPG)

**Comment by chasebrewsky** [comment]
That's weird. When the docker compose file runs it should be pulling from` cyphon.env` file to configure both RabbitMQ and Cyphon. It doesn't read from `default.py`, so don't worry about that. It is reading from `conf.py` to set RabbitMQ though, so just to test it out try setting the settings in `conf.py` to:

```
RABBITMQ = {
    'HOST': os.getenv('RABBITMQ_DEFAULT_HOST', 'rabbit'),
    'VHOST': os.getenv('RABBITMQ_DEFAULT_VHOST', 'cyphon'),
    'USERNAME': os.getenv('RABBITMQ_DEFAULT_USER', 'guest'),
    'PASSWORD': os.getenv('RABBITMQ_DEFAULT_PASS', 'guest'),
    'EXCHANGE': 'cyphon',
    'DURABLE': True,
}
```

That way it matches the settings in `cyphon.env`. If that fixes it, that means that the `env` file isn't getting read into the Cyphon container.

**Comment by p3nreel** [comment]
Thanks Chase, I made the change but getting the same error. Question for you though. I followed all the instructions from http://cyphon.readthedocs.io/en/latest/tutorials/email-tutorial.html on "generating alerts from email" and as you can see from the screenshot below, Cyphon is ingesting the emails but when you go to the console, there are no alerts. If Cyphon is receiving the email alerts, we should be getting alerts in the console correct? or is there additional steps that need to be done that wasn't mentioned on the tutorial?
![alert 1](https://user-images.githubusercontent.com/19589960/43093033-fbce640e-8e7c-11e8-8860-133d96cb7e94.JPG)
![no alerts](https://user-images.githubusercontent.com/19589960/43093042-01d23948-8e7d-11e8-8235-01ed08814a7b.JPG)

**Comment by p3nreel** [comment]
Just curious, after making the previous change, what command would you run for Cyphon to accept the new changes?
