### ISSUE TITLE
Not able to find cyphon service

### ISSUE THREAD

**Issue by Aagosh** [controlscanmdr/cyphon#606]
When i run the command "$ sudo systemctl status cyphon"  , it says that no such file or directory exists.

**Comment by p3nreel** [comment]
Hi Aagosh, did you install via docker? I usually run the below command to check the status of the docker service.  
![capture](https://user-images.githubusercontent.com/19589960/42579422-4c93fc4a-84f6-11e8-939a-f84e1e1de5b7.JPG)
![capture1](https://user-images.githubusercontent.com/19589960/42579429-4df69192-84f6-11e8-867f-4703ce0fe6dc.JPG)

**Comment by Aagosh** [comment]
Hi p3nreel. Thank you for replying. Yes, I installed it through the docker service and it is running fine. Please find below the screenshot of the output, when i ran the command "$ sudo systemctl status docker.service -l". 

![image](https://user-images.githubusercontent.com/41115767/42618353-5fb50fb2-85d2-11e8-94c2-e6516021d0da.png)
