### ISSUE TITLE
Try to start Docker on Mac: can't start service elasticsearch

### ISSUE THREAD

**Issue by gudsaf** [controlscanmdr/cyphon#684]
Got the error when try to `docker-compose up -d`

> $ docker-compose up -d
> cyphondock_postgres_1 is up-to-date
> cyphondock_geoip_1 is up-to-date
> cyphondock_rabbit_1 is up-to-date
> Creating cyphondock_elasticsearch_1 ... error
> 
> ERROR: for cyphondock_elasticsearch_1  Cannot start service elasticsearch: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/opt/cyphon/cyphondock/config/elasticsearch/jvm.options\\\" to rootfs \\\"/var/lib/docker/overlay2/03cb6b8ddefed9a724a3c3db57dfe95b421680e927eb2c7dab6ec22844eb3a95/merged\\\" at \\\"/var/lib/docker/overlay2/03cb6b8ddefed9a724a3c3db57dfe95b421680e927eb2c7dab6ec22844eb3a95/merged/usr/share/elasticsearch/config/jvm.options\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
> 
> ERROR: for elasticsearch  Cannot start service elasticsearch: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/opt/cyphon/cyphondock/config/elasticsearch/jvm.options\\\" to rootfs \\\"/var/lib/docker/overlay2/03cb6b8ddefed9a724a3c3db57dfe95b421680e927eb2c7dab6ec22844eb3a95/merged\\\" at \\\"/var/lib/docker/overlay2/03cb6b8ddefed9a724a3c3db57dfe95b421680e927eb2c7dab6ec22844eb3a95/merged/usr/share/elasticsearch/config/jvm.options\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

Mac OS Mojave 10.14.2
Docker Desktop Community 2.0.0.0-mac81 (29211)
Compose: 1.23.2

**Comment by fatalglitch** [comment]
You need to update the docker-compose files to reference the proper filesystem locations based on your installation.
