### ISSUE TITLE
Securing the installation

### ISSUE THREAD

**Issue by callahan22** [controlscanmdr/cyphon#690]
Hi,

The steps here: https://cyphondock.readthedocs.io/en/latest/securing-cyphon.html#cyphon-env are confusing. Following the steps, I've updated my /opt/cyphon/cyphondock/config/env/cyphon.env file with my own config:

```
POSTGRES_HOST=postgres
POSTGRES_DB=cyphon
POSTGRES_USER=postgres-cyphon
POSTGRES_PASSWORD=mysecretpassword

RABBITMQ_DEFAULT_HOST=rabbit
RABBITMQ_DEFAULT_VHOST=cyphon
RABBITMQ_DEFAULT_USER=rabbit-cypton
RABBITMQ_DEFAULT_PASS=mysecretpassword
```
I've run docker-compose down to bring the containers down, delete the volumes to ensure that the old database is removed and then docker-compose up -d to bring them back up. The environment variables are ingested and postgres is set up with the new username and password.
Looking at sudo docker-compose logs -f cyphondock_cyphon_1, there is the expected error shown below (expected because I've not told the cyphon container what the new username and password is for the database).
`An error occurred while closing Streams: FATAL:  password authentication failed for user "postgres-cyphon"`
So, from that, I'm assuming that I need to edit the: /opt/cyphon/cyphondock/config/cyphon/settings/conf.py file here:
```
POSTGRES = {
    'NAME': os.getenv('POSTGRES_DB', 'cyphon'),
    'USER': os.getenv('POSTGRES_USER', 'postgres'),
    'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
    'HOST': os.getenv('POSTGRES_HOST', 'postgres'),  # e.g., 'localhost'
    'PORT': os.getenv('POSTGRES_PORT', '5432'),
}
```
From the above, I'm reading that as "Get the defined env variable for POSTGRES_DB, POSTGRES_USER, etc but if they are missing, use the string defined next."
So my logic says that I can just use the config below to let cyphon know the DB creds.
```
POSTGRES = {
    'NAME': os.getenv('POSTGRES_DB'),
    'USER': os.getenv('POSTGRES_USER'),
    'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
    'HOST': os.getenv('POSTGRES_HOST'),
    'PORT': os.getenv('POSTGRES_PORT'),
}
```
The instructions suggest that I don't need to change the conf.py file if I set the variables in the env file but this leaves me with 2 questions:
1). How will crypton connect to the postgres DB?
2). Where to I configure the new postgres details for crypton to use?

Lastly, once I have the initial build, am I supposed to then run docker-compose up -d again using the prod compose file? I can't find any reference to thats the process or not.

Thanks.

**Comment by fatalglitch** [comment]
From what I am reading, it seems like you are trying to take an existing TEST/DEV environment, and convert it in place to a "production" environment. This is not at all recommended.

Instead, create a new environment, and get all the proper settings in place before running the docker-compose scripts. There's a LOT more to consider when running anything docker in production. As an example, never use latest tags on compose files, and ensure you are hard locking dependencies and etc. so they can be properly tested prior to an unexpected or expected upgrade.

The steps we have outlined are suggestions for Production usage, but by no means are they an exhaustive list.
