### ISSUE TITLE
Cyphon Admin Page doesn't work properly

### ISSUE THREAD

**Issue by sathishkgit** [controlscanmdr/cyphon#695]
http://lcoalhost:8000/admin/ page works properly only once during fresh installation. After that the admin page keeps loading and gets timeout. But it works once in a while very randomly. 

But the subsequent pages works properly like http://lcoalhost:8000/admin/bottles.

Anybody facing same issue and help with the resolution?

**Comment by fatalglitch** [comment]
We haven't seen this issue before, can you provide the logs from Cyphon container?
