### ISSUE TITLE
Unable to create Cyphon Production Environment

### ISSUE THREAD

**Issue by gabetfmx** [controlscanmdr/cyphon#696]
When running the sudo docker-compose up -d command i get an error telling me it cant find the docker-compose.yml file. When i do a ls -al the file is there. Not sure what to do.
![Cyphon Error](https://user-images.githubusercontent.com/56093684/66080143-1b8b9e00-e52b-11e9-88fc-1e42a7cf0dab.PNG)

**Comment by fatalglitch** [comment]
Try sudo'ing to root, then run docker-compose from /opt/cyphon/cyphondock. It's possible the that trying to run docker-compose with sudo is resetting your path and so the sudo process doesn't see the same directory you are in
