### ISSUE TITLE
Unable to start Cyphon Service on ISO 

### ISSUE THREAD

**Issue by alexandrecaio** [controlscanmdr/cyphon#699]
Hi, I'm installed the VM with ISO avaliable on official site and when I tried to use "sudo systemctl start cyphon" got a error.

I installed Docker and Docker Compose on VM...

![Laboral](https://user-images.githubusercontent.com/20290444/68769645-6f49d680-0603-11ea-963d-592e5f560bc0.png)

**Comment by alexandrecaio** [comment]
![ErroISO](https://user-images.githubusercontent.com/20290444/69240259-d7a43500-0b7a-11ea-93f9-645efa6751ac.png)
After some configs in VM, i got the same error that i have with Cyphondock installation:
https://github.com/controlscanmdr/cyphondock/issues/90

**Comment by fatalglitch** [comment]
The ISO images and underlying setups have been recently updated due to multiple dependency changes. Please re-download the ISO for further testing. If you are still having issues, please make sure you are following the instructions on ReadTheDocs, and then post another issue

**Comment by alexandrecaio** [comment]
@fatalglitch I have looked for the new ISO, but its the same that I downloaded before...
