### ISSUE TITLE
Virtual Machine advertised on cyphon.io not downloadable

### ISSUE THREAD

**Issue by supersexy** [controlscanmdr/cyphon#700]
https://s3.amazonaws.com/cyphon-public/vms/Cyphon-20171011.ova

is not available. 

is this project dead?

**Comment by fatalglitch** [comment]
The OVA has been deprecated while we work on updating the Docker and ISO images. If you are creating a VM, use the ISO image instead

**Comment by supersexy** [comment]
Thanks for the info, please update your website and write a blogpost about your progress, project looks interesting!
