### ISSUE TITLE
Unable to run the cyphon in virtualbox 

### ISSUE THREAD

**Issue by amitbatajoo** [controlscanmdr/cyphon#704]
Hello, I am very new in Linux.
-------------------------------------------------------
I am trying to implement cyphon in my virtual box Ubuntu Server. 
I have installed cyphon iso from site and setup in virtualbox. I followed all the instruction from the document (https://cyphon.readthedocs.io/en/latest/getting-started/install-cyphon.html#virtual-machine). 
I have also downloaded the GeoIP db file for city and country and save inside /usr/share/GeoIP file.
I tried to run the project using docker commnad. 
I am getting following error.
Please HELP ME!!!!
------------------------------------------------------------
Error
cyphon@cyphon:/opt/cyphon/cyphondock$ sudo docker-compose -f docker-compose.yml up
Building geoip
Step 1/16 : FROM alpine
 ---> e7d92cdc71fe
Step 2/16 : MAINTAINER Tom Callahan <tcallahan@controlscan.com>
 ---> Using cache
 ---> 355e59840744
Step 3/16 : ENV GEOIP_BASE_URL      http://geolite.maxmind.com/download/geoip/database
 ---> Using cache
 ---> 65cbc585b036
Step 4/16 : ENV GEOIP_CNTR_DB       GeoLite2-Country.mmdb
 ---> Using cache
 ---> dcb578e1a745
Step 5/16 : ENV GEOIP_CITY_DB       GeoLite2-City.mmdb
 ---> Using cache
 ---> 3a07561e88dd
Step 6/16 : ENV GEOIP_DB_DIR        /usr/share/GeoIP
 ---> Using cache
 ---> b33aeeb0f74e
Step 7/16 : ENV GEOIPUPDATE_VER     "4.0.6"
 ---> Using cache
 ---> b4a32251cf4b
Step 8/16 : ADD ${GEOIP_BASE_URL}/${GEOIP_CNTR_DB}.gz /tmp/
ERROR: Service 'geoip' failed to build: ADD failed: Get http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz: dial tcp: lookup geolite.maxmind.com on 192.168.10.1:53: no such host
cyphon@cyphon:/opt/cyphon/cyphondock$
------------------------------------------------------------
If my process is wrong than, please let me know and suggest me, how can I easily install in ubuntu server and run the project.

Thank you in advance.

**Comment by fatalglitch** [comment]
This issue has been resolved with an update to the GeoIP Docker build.
