### ISSUE TITLE
Cyphon fails to build due to libffi dependency issue

### ISSUE THREAD

**Issue by anhtn512** [controlscanmdr/cyphon#711]
Cyphon is failing to build due to install libffi. the log of installation in bellow:

``Step 10/23 : RUN apk add -U --no-cache       --repository http://dl-5.alpinelinux.org/alpine/edge/main/       --repository http://dl-5.alpinelinux.org/alpine/edge/testing/       --repository http://dl-5.alpinelinux.org/alpine/edge/community/       binutils       gdal       postgis       proj-dev       py3-gdal       su-exec && ln -s /usr/lib/libgdal.so.20 /usr/lib/libgdal.so && ln -s /usr/lib/libgeos_c.so.1 /usr/lib/libgeos_c.so && apk add -U --no-cache       --repository http://dl-5.alpinelinux.org/alpine/edge/main/       --repository http://dl-5.alpinelinux.org/alpine/edge/testing/       --repository http://dl-5.alpinelinux.org/alpine/edge/community/       -t build-deps       build-base       libffi-dev       libressl-dev       openssl-dev       linux-headers       musl-dev       postgis       postgresql-dev       python3-dev       jpeg-dev       zlib-dev       tiff-dev && pip install --upgrade pip && pip install -r $CYPHON_HOME/requirements.txt && apk del build-deps && python -m nltk.downloader -d /usr/local/share/nltk_data punkt wordnet
 ---> Running in 785ef0a8f8aa
fetch http://dl-5.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-5.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-5.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libffi-3.2.1-r6:
    conflicts: libffi-3.3-r1
    satisfies: .python-rundeps-20200324.032015[so:libffi.so.6]
  libffi-3.3-r1:
    conflicts: libffi-3.2.1-r6
    satisfies: llvm10-libs-10.0.0-r2[so:libffi.so.7]
ERROR: Service 'cyphon' failed to build: The command '/bin/sh -c apk add -U --no-cache       --repository http://dl-5.alpinelinux.org/alpine/edge/main/       --repository http://dl-5.alpinelinux.org/alpine/edge/testing/       --repository http://dl-5.alpinelinux.org/alpine/edge/community/       binutils       gdal       postgis       proj-dev       py3-gdal       su-exec && ln -s /usr/lib/libgdal.so.20 /usr/lib/libgdal.so && ln -s /usr/lib/libgeos_c.so.1 /usr/lib/libgeos_c.so && apk add -U --no-cache       --repository http://dl-5.alpinelinux.org/alpine/edge/main/       --repository http://dl-5.alpinelinux.org/alpine/edge/testing/       --repository http://dl-5.alpinelinux.org/alpine/edge/community/       -t build-deps       build-base       libffi-dev       libressl-dev       openssl-dev       linux-headers       musl-dev       postgis       postgresql-dev       python3-dev       jpeg-dev       zlib-dev       tiff-dev && pip install --upgrade pip && pip install -r $CYPHON_HOME/requirements.txt && apk del build-deps && python -m nltk.downloader -d /usr/local/share/nltk_data punkt wordnet' returned a non-zero code: 6
anhtn@ubuntu:/opt/cyphondock$ ^C``
![image](https://user-images.githubusercontent.com/24378573/79367447-1eeef000-7f78-11ea-8acf-3578068898f0.png)

Please help me to check it. thank you ^^

**Comment by mikelv702** [comment]
Same issue here.

**Comment by mikelv702** [comment]
I was able to get past this by removing from the Dockerfile
      --repository http://dl-5.alpinelinux.org/alpine/edge/main/ \
      --repository http://dl-5.alpinelinux.org/alpine/edge/testing/ \
      --repository http://dl-5.alpinelinux.org/alpine/edge/community/ \

**Comment by phuong7809** [comment]
I did as you instructed, but it's still the same error
![image](https://user-images.githubusercontent.com/40901463/79950315-167b4580-84a1-11ea-9645-7fdfab3824cc.png)

**Comment by anhtn512** [comment]
> I was able to get past this by removing from the Dockerfile
> --repository http://dl-5.alpinelinux.org/alpine/edge/main/
> --repository http://dl-5.alpinelinux.org/alpine/edge/testing/
> --repository http://dl-5.alpinelinux.org/alpine/edge/community/ \
> 
> I also needed to update the requirements file replacing maxminddb==1.4.1 with
> maxminddb==1.5.2

The bug have fixed with this change ^^
thank you

**Comment by DestruidorPT** [comment]
I have a problem, I did what @mikelv702 said, but that gives the same error with the same command even though I changed the file.
Did @mikelv702 or @anhtn512 make any commands for him to notify the program that the file has been changed?
